### ISSUE TITLE
Error at Start

### ISSUE THREAD

**Issue by philippgerbig** [b6pzeusbc54tvhw5jgpyw8pwz2x6gs/sinopia-pm2-starter#1]
See this:

`$ sinopia-pm2-starter start
No config file

/usr/lib/node_modules/sinopia-pm2-starter/bin/sinopia-pm2-starter.js:59
og("If you want to use your serverInfo, sinopia-pm2-starter --help".yellow() )
                                                                    ^
TypeError: Object If you want to use your serverInfo, sinopia-pm2-starter --help has no method 'yellow'
    at Object.<anonymous> (/usr/lib/node_modules/sinopia-pm2-starter/bin/sinopia-pm2-starter.js:59:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3`

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Thanks for your reporting. I will check and fix it.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@philippgerbig , I changed the command line color module to colors for resolving this issue.
Thank you.
